### ISSUE TITLE
Incorrect ExtensionUtil classes

### ISSUE THREAD

**Issue by rbaugh** [mjwconsult/civicrm-payflowpro#2]
Errors due to ExtensionUtil classes that are from other extensions.
CRM_AdvancedEvents_ExtensionUtil
CRM_Stripe_ExtensionUtil

**Comment by mattwire** [comment]
Thanks. Fixed via https://github.com/mjwconsult/civicrm-payflowpro/commit/644acaaf2f0eb023eb8dfeba204568aa13a1bef9
